# Generated by Django 5.0.1 on 2024-01-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_data', '0003_alter_taskdetail_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='task_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
